# (PART) Season

# Schedule

```{r}

dt_season_show <- dt_season[course=='full' & !(is_champ), .(`Race #` = race_number,
                            Date = date_ymd,
                            `Event type` = race_type,
                            cancelled,
                            cancelled_reason,
                            have_results)]

dt_season_show[(cancelled), Note:= paste0("Cancelled due to ", cancelled_reason)]
dt_season_show[!(cancelled) & !(have_results), Note := "webscorer data not available"]
dt_season_show[is.na(Note), Note := ""]

knitr::kable(dt_season_show[, .(`Race #`,
                                Date,
                                `Event type`,
                                Note
                                )])
```


# Participation - Total

```{r}
n_entries_all_season <- nrow(dt_all_long[(started) & part == "Swim"])
```


There have been `r n_entries_all_season` entries this season from `r n_athletes_season` athletes. 

```{r}

htmltools::tags$iframe(
  src = "plot_participation_hist.html", 
  scrolling = "yes",
  frameBorder = "0",
  width = "100%",
  height = 500
)
```

```{r}

htmltools::tags$iframe(
  src = "tab_participation.html", 
  scrolling = "yes",
  frameBorder = "0",
  width = "100%",
  height = 1000
)
```

# Participation - Trends


```{r}

htmltools::tags$iframe(
  src = "plot_participation.html", 
  scrolling = "yes",
  frameBorder = "0",
  width = "100%",
  height = 1000
)
```
