# Race Results

## Dec 5 {#r-2020-12-05}

Overall times



```{r}
p <- ggplot(dt_times_long[order(place_overall)][!(data_problem)],
            aes(x = duration_mins, y = - place_overall, fill = part, group = Name, text = tooltext)) +
    geom_col(orientation = "y") +
    # geom_col(aes(x = swim_duration/60 + ride_duration/60, y = Name),width = 2, orientation = "y", fill = "#3B8544") +
    # geom_col(aes(x = swim_duration/60, y = Name),width = 2, orientation = "y", fill = "#2E63BC")  +
      scale_fill_manual("Part",
                        labels = c(Swim = "Swim",
                                   Ride = "Ride",
                                   Run = "Run"),
                        values = c(Swim = "#2E63BC",
                                   Ride = "#3B8544",
                                   Run = "#BF5324")) +
      scale_x_continuous("Time (mins)", breaks = seq(0,100, 10), minor_breaks = seq(0,100, 5)) +
      scale_y_continuous("Athlete", breaks = -dt_times_long$place_overall,
                         labels = dt_times_long$place_name) +
  theme_minimal()


ggplotly(p,width = 800, height = 700, tooltip = "text")
```

Some results have been omitted due to webscorer data issues:

```{r}
knitr::kable(dt_times_long[(data_problem), .(Name, part, duration)][order(Name, part)], caption = "Results omitted from plot because of data issues.")
```

