
# Create Athlete results Rmd -------------------------------------------------



header <- paste0({
"# (PART) Competitor Results {#athletes}

<!-- Do not edit this file -->
<!-- This Rmd file is created using make_athlete_rmd.R -->

"
})


repeated <- foreach (k=athletes_ordered, .combine = paste0 ) %do% {
  
  
  k_ref <- gsub(pattern = " ", "-", k)  
  k_ref <- gsub(pattern = "'", "", k_ref) 

  k_courses <- unique(dt_all_long[Name==k, .(course)]$course)
  n_courses <- length(k_courses)

  
  
  
  paste0(
    "
",
"# ", k, " {#a-", k_ref, "}

All races in the season are shown below, if more than one type of course (Full, Intermediate, or Double Distance) has been entered then separate plots are shown.

",

'```{r}
htmltools::tags$iframe(
  src = "',paste0(k,".html"),'", 
  scrolling = "no", 
  seamless = "seamless",
  frameBorder = "0",
  width = "100%",
  height = "',500*n_courses,'"
)
```



Please let me know if any split times have been incorrectly flagged as invalid.


',
  
foreach(j=k_courses, .combine=paste0) %do% {
  
  n_entries <- nrow(dt_all_long[Name==k & course ==j & part =="Swim"])
  
  
  j_course_nice <- c("Double Distance","Full","Intermediate")[which(j==c("double","full","int"))]

  paste0(
'

### Detailed results for ',j_course_nice,' course

Season records are show in gold, season PBs are shown in pink, and invalid times in grey. Ranks compare efforts by this athlete over the season.

```{r}
htmltools::tags$iframe(
  src = "',paste0("tab_", k,"_",j,".html"),'", 
  scrolling = "yes", 
  seamless = "seamless",
  frameBorder = "0",
  width = "100%",
  height = "',n_entries*50+200,'"
)
```

'
  )

}
)
  
  
}


write(paste0(header, repeated),file = "03-athlete_generated.Rmd")
