
# Create Race results Rmd -------------------------------------------------


header <- paste0({
"# (PART) Race Results {#races}

<!-- Do not edit this file -->
<!-- This Rmd file is created using make_race_rmd.R -->

"
})


races <- foreach (i=rev(race_numbers), .combine = paste0 ) %do% {
  
  i_date_file <- format(dt_season[race_number == i]$date_ymd[1], "%Y-%m-%d")
  i_date <- format(dt_season[race_number == i]$date_ymd[1], "%b %d")
  
  i_race_type <- dt_season[race_number == i]$race_type[1]
  
  # Available course results - double first if available
  i_courses <- dt_season[race_number==i]$course
  i_courses_nice <- dt_season[race_number==i]$course_nice
  
  if("double" %in% i_courses) {
    i_courses <- c("double","full","int")
    i_courses_nice <- c("Double Distance","Full","Intermediate")
    }
  
  
  paste0(
    "
",
"# ", i,": ", i_date, ifelse(i_race_type=="Standard", "", paste0(" - ",i_race_type))," {#r-", i_date_file, "}
    
    ",
  foreach (j=i_courses, .combine = paste0 ) %do% {
    
paste0(
'
## ',i_courses_nice[which(j==i_courses)],'

',

'```{r}
htmltools::tags$iframe(
  src = "',paste0(i_date_file,"_",j,".html"),'", 
  scrolling = "no", 
  seamless = "seamless",
  frameBorder = "0",
  width = "100%",
  height = "700"
)
```
    
    '
)
  
    
  }
)
  
  
}

write(paste0(header, races),file = "01-races_generated.Rmd")
