
# Create record pages -----------------------------------------------------

header <- paste0({
"
  
<!-- Do not edit this file -->
<!-- This Rmd file is created using make_record_rmd.R -->

"
})


body <- foreach(j = c("full", "int","double"), .combine = paste0 ) %do% {
  
  
  j_course_nice <- c("Double Distance","Full","Intermediate")[which(j==c("double","full","int"))]
  
  
  
  paste0("\n# Best Times - ", j_course_nice,"
\n## Overall\n\n",
"The best valid times for each competitor are ranked in the plot and table below.\n",
'Disclaimer: These results are based on webscorer data but are completely unofficial. `r if(some_weeks_missing_full) paste0("Results are not available for the following weeks: ", paste0(weeks_missing_int, collapse= ", "))`.\n',
'
```{r}
n_athletes <- nrow(dt_all_long[course=="',j,'" & (isPB_overall) & part=="Swim"])

htmltools::tags$iframe(
  src = "plot_record_',j,'.html", 
  scrolling = "no", 
  seamless = "seamless",
  frameBorder = "0",
  width = "100%",
  height = 150 + 16*n_athletes
)
```
\n',
  
  foreach(l = c("overall","Swim","Ride","Run"), .combine = paste0 ) %do%  {
    
    
    paste0(ifelse(l=="overall","",paste0('## ', l)),
           "\n\nSeason records are show in gold, split PBs are shown in pink, and invalid times in grey.",
           if(l!="overall") paste0(" Ranks for other parts and overall are provided only for PBs."),
           if(l=="overall") paste0(" Ranks for individual parts are provided only for PBs."),
'

```{r}
htmltools::tags$iframe(
  src = "tab_record_',l,'_',j,'.html", 
  scrolling = "yes", 
  #seamless = "seamless",
  frameBorder = "0",
  width = "100%",
  height = "700"
)
```
\n')
    
    
    
  }
  
  )
}

write(paste0(header, body),file = "01-records_generated.Rmd")
