
# Create Race results Rmd -------------------------------------------------


header <- paste0({
"# (PART) Race Results {#races}

<!-- Do not edit this file -->
<!-- This Rmd file is created using make_race_rmd.R -->

"
})


races <- foreach (i=rev(race_numbers), .combine = paste0 ) %do% {
  
  
  n_athletes <- nrow(dt_all_long[(started) & part == "Swim" & race_number == i])
  
  n_new_athletes <- nrow(dt_all_long[(started) & part == "Swim" & entries_cumulative==1 & race_number == i])
  text_new_athletes <- if(i==1 | n_new_athletes == 0) {
    ""
  } else {
    paste0(", ", n_new_athletes, " for the first time this season")
  }
  
  i_date_file <- format(dt_season[race_number == i]$date_ymd[1], "%Y-%m-%d")
  i_date <- format(dt_season[race_number == i]$date_ymd[1], "%b %d")
  
  i_race_type <- dt_season[race_number == i]$race_type[1]
  
  # Available course results - place club championship or double-distance first
  
  dt_season_i <- dt_season[race_number==i][order(-is_champ,course )]
  
  i_courses <- dt_season_i$course
  i_courses_nice <- dt_season_i$course_nice
  i_is_champ <- dt_season_i$is_champ
  
  j_options <- seq(length(i_courses))
  
  paste0(
    "
",
"# ", i,": ", i_date, ifelse(i_race_type=="Standard", "", paste0(" - ",i_race_type))," {#r-", i_date_file, "}\n\n",

"A total of ", n_athletes,  " competitors entered", text_new_athletes, ".\n\n",

  foreach (j_counter=j_options, .combine = paste0 ) %do% {
    
    j <- i_courses[j_counter]
    j_is_champ <- i_is_champ[j_counter]
    
    dt_i <- dt_all_long[race_number== i & course == j & j_is_champ == (is_champ)][(started)]
    
    n_athletes <- length(unique(dt_i[part=="Swim"]$Name))
    
    dt_pb_split_new <- dt_i[(isNewPB_split), .(.N), by = part]
    
    dt_pb_split_new[part=="Swim", `:=`(where="in the pool", ord=1)]
    dt_pb_split_new[part=="Ride", `:=`(where="on the bike", ord=2)]
    dt_pb_split_new[part=="Run", `:=`(where="on the run", ord=3)]
    
    dt_pb_split_new[, phrase := paste0(N, " ", where)]
    
    setorder(dt_pb_split_new, ord)
    
    pb_split_sentence <- list_with_and(dt_pb_split_new$phrase)
    
    n_pb_splits_new <- sum(dt_pb_split_new$N)
    pb_overall_new <- nrow(dt_i[(isNewPB_overall) & part=="Swim"])
    
    
    
paste0(
'
## ',i_courses_nice[j_counter],'\n\n',

n_athletes,' competitors entered the course',
if(pb_overall_new!=0 | n_pb_splits_new !=0) ", achieving ",
list_with_and(
c(if(pb_overall_new!=0) {paste0(pb_overall_new,' new overall PBs')},
if(n_pb_splits_new!=0) {
  paste0( n_pb_splits_new, ' new split PBs: ', pb_split_sentence)
  })),
'.',

'\n\n',

'```{r}
htmltools::tags$iframe(
  src = "',paste0(i_date_file,"_",j,ifelse(j_is_champ, "_champ",""),".html"),'", 
  scrolling = "no", 
  seamless = "seamless",
  frameBorder = "0",
  width = "100%",
  height = "',150 + 16*n_athletes,'"
)
```
    
    ',

# tables
  '

### Detailed results for ',i_courses_nice[j_counter],' course

Season records are show in gold, season PBs are shown in pink, and invalid times in grey. Ranks compare efforts in this race.

```{r}
htmltools::tags$iframe(
  src = "',paste0("tab_race_", i,"_",j,ifelse(j_is_champ, "_champ",""),".html"),'", 
  scrolling = "yes", 
  seamless = "seamless",
  frameBorder = "0",
  width = "100%",
  height = "',n_athletes*50+200,'"
)
```

'
)
  
    
  }
)
  
  
}

write(paste0(header, races),file = "02-races_generated.Rmd")
