
# Create Athlete results Rmd -------------------------------------------------



header <- paste0({
"# (PART) Competitor Results {#athletes}

<!-- Do not edit this file -->
<!-- This Rmd file is created using make_race_rmd.R -->

"
})


races <- foreach (k=athletes_ordered, .combine = paste0 ) %do% {
  
  
  k_ref <- gsub(pattern = " ", "-", k)  
  k_ref <- gsub(pattern = "'", "", k_ref)  

  
  
  
  paste0(
    "
",
"# ", k, " {#a-", k_ref, "}
    
    
All entries in the season are shown below, if more than one type of course (Full, Intermediate, or Double Distance) has been entered then  separate plots are shown.

Please let me know if any split times have been incorrectly flagged as invalid.

    ",

    
paste0(
'
<div id="content">
  <div class="desktop">
```{r}
list_plotly_athlete$`',k,'`
```

  </div>

  <div class="mobile">
```{r fig.cap="An interactive version of this plot is available on desktop or tablet devices."}
knitr::include_graphics("figures/athlete/',k,'.pdf")
```

  </div>
</div>'
)
  
    

)
  
  
}

# cat(header, races)

write(paste0(header, races),file = "02-athlete_generated.Rmd")
